matrix:
 include:
  - os: linux
    language: python
    python: "3.5"
  - os: linux
    language: python
    python: "3.6"
  - os: osx
    osx_image: "xcode10.1"
    language: generic
    before_install:
    - mkdir -p /Users/travis/.matplotlib
    - "echo 'backend: TkAgg' > /Users/travis/.matplotlib/matplotlibrc"
    - travis_retry wget "http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh" -O miniconda.sh
    - "bash miniconda.sh -b -p $HOME/miniconda"
    - "export PATH=$HOME/miniconda/bin:$PATH"
    - "conda create -y -n elfi python=3.6 scipy"
    - "source activate elfi"

cache: pip

install:
  - pip install numpy
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - ipcluster start -n 2 --daemon
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        travis_wait 13 make test;
    else
        make test;
    fi'
  - ipcluster stop
